# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-26 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YubikeyAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yubikey_id', models.CharField(max_length=12, null=True, unique=True)),
                ('user_id', models.IntegerField(unique=True)),
                ('user_name', models.CharField(max_length=100, null=True)),
                ('otp_disabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
